name: showyourwork
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.5
  - pip=21.0.1
  - python=3.9
  - pandas=1.4.1
  - matplotlib==3.5.1
  - pyyaml==5.4.1
  - mpmath==1.2.1
  - openpyxl==3.0.9
